"""Contrats de données versionnés partagés par tous les services de la plateforme.

Le cœur métier ne dépend que de ces contrats : jamais d'une implémentation
de provider (Hermes, Claude, Codex, ...).
"""

CONTRACTS_VERSION = "1.0"

from .auth import (  # noqa: F401
    AuthenticatedUser,
    AuthSessionResponse,
    AuthStatusResponse,
    LoginRequest,
    LogoutResponse,
    OwnerBootstrapRequest,
)
from .enums import (  # noqa: F401
    AgentStatus,
    MemoryClassification,
    MemoryScope,
    PermissionRole,
    ProviderKind,
    SessionScope,
    SharingPolicy,
    TaskRunStatus,
    TaskStatus,
)
from .entities import (  # noqa: F401
    AgentInstance,
    Department,
    Organization,
    Project,
    Task,
    TaskRun,
    Team,
    TeamMember,
    Workspace,
)
from .conversations import (  # noqa: F401
    ConversationCreate,
    ConversationDetail,
    ConversationList,
    ConversationPatch,
    ConversationStatus,
    ConversationSummary,
    ConversationTurn,
    ConversationTurnCreate,
    ConversationTurnList,
    ConversationTurnStatus,
    HermesConnectionDiagnostic,
    HermesNativeListing,
    HermesNativeListingStatus,
    HermesNativeSkill,
    HermesNativeToolset,
)
from .events import (  # noqa: F401
    EVENT_SCHEMA_VERSION,
    Event,
    EventEnvelope,
    EventPage,
    StreamEvent,
)
from .memory import MemoryItem  # noqa: F401
from .missions import (  # noqa: F401
    AutonomyMode,
    EvidenceCreate,
    MissionAcceptanceDecision,
    MissionAutonomy,
    MissionBudget,
    MissionComment,
    MissionCommentCreate,
    MissionCreate,
    MissionDetail,
    MissionEvidence,
    MissionResource,
    MissionRetryRequest,
    MissionRun,
    MissionRunStatus,
    MissionStopResponse,
    MissionSummary,
    TechnicalValidation,
    UserAcceptance,
)
from .providers import (  # noqa: F401
    ContextSummary,
    ContextSummaryRequest,
    EvaluationRequest,
    EvaluationResult,
    PlanningRequest,
    PlanningResult,
    PlanRevisionRequest,
    PlanStep,
    ProviderDescriptor,
    ProviderHealth,
)
from .sessions import SessionContext  # noqa: F401
from .service_urls import (  # noqa: F401
    ServiceOriginError,
    normalize_service_origin,
)
from .operations import (  # noqa: F401
    ApprovalActionEnvelope,
    ApprovalAction,
    ApprovalDecision,
    ApprovalExecutionCheck,
    ApprovalRequest,
    ApprovalRequestCreate,
    ApprovalStatus,
    ApprovalValidationResult,
    Artifact,
    ArtifactCreate,
    ArtifactLink,
    ArtifactPage,
    ArtifactSummary,
    LockAcquireRequest,
    LockOwnerRequest,
    ResourceLock,
    ResourceType,
)
from .testing import (  # noqa: F401
    REPORTER_EVENTS_MAX,
    TEST_ERROR_MAX_CHARS,
    TEST_STEPS_MAX,
    ReporterAttachment,
    ReporterEvent,
    TestCaseResult,
    TestIngestRequest,
    TestOutcome,
    TestRunDetail,
    TestRunStatus,
    TestRunSummary,
    TestStatus,
    TestStep,
    TestTotals,
)
from .workers import (  # noqa: F401
    WorkerCapability,
    WorkerClaimRequest,
    WorkerHeartbeatRequest,
    WorkerHeartbeatResponse,
    WorkerLeaseResponse,
    WorkerRegistrationRequest,
    WorkerRegistrationResponse,
    WorkerSnapshot,
    WorkerStatus,
)
from .mcp import (  # noqa: F401
    SLUG_PATTERN,
    McpBinding,
    McpBindingCreate,
    McpBindingPatch,
    McpCatalogEntry,
    McpDiscoveredTool,
    McpDiscovery,
    McpExecutionLocation,
    McpExport,
    McpExportFormat,
    McpHttpConfig,
    McpImportApplyRequest,
    McpImportApplyResult,
    McpImportEntry,
    McpImportFormat,
    McpImportPreview,
    McpImportPreviewRequest,
    McpImportSecretCandidate,
    McpProbe,
    McpProbeAuthorization,
    McpProbeDecision,
    McpProbeResult,
    McpProbeStatus,
    McpRevisionDiff,
    McpRevokeRequest,
    McpRiskFlag,
    McpRiskLevel,
    McpRollbackRequest,
    McpServerConfig,
    McpServerCreate,
    McpServerDetail,
    McpServerRevision,
    McpServerRevisionCreate,
    McpServerStatus,
    McpServerSummary,
    McpSourceKind,
    McpStdioConfig,
    McpTransport,
    SecretRef,
    validate_slug,
)
from .skills import (  # noqa: F401
    SkillApproveRequest,
    SkillBinding,
    SkillBindingCreate,
    SkillCatalogEntry,
    SkillDependencies,
    SkillDetail,
    SkillFile,
    SkillFileContent,
    SkillFindingLevel,
    SkillImportRequest,
    SkillKind,
    SkillRevision,
    SkillRevisionCreate,
    SkillRevisionDiff,
    SkillRevokeRequest,
    SkillRollbackRequest,
    SkillScanFinding,
    SkillSearchResult,
    SkillSource,
    SkillSourceArchive,
    SkillSourceDirectory,
    SkillSourceFile,
    SkillSourceGithub,
    SkillSourceKind,
    SkillSourceManual,
    SkillStatus,
    SkillSummary,
)
from .secrets import (  # noqa: F401
    SECRET_NAME_PATTERN,
    SecretCreate,
    SecretRotate,
    SecretScopeType,
    SecretSummary,
    SecretsStatus,
)
from .extensions import (  # noqa: F401
    ProjectExtensions,
    ProjectMcpExtension,
    ProjectSkillExtension,
)
from .redaction import (  # noqa: F401
    MAX_REDACTION_DEPTH,
    MIN_REDACTED_VALUE_CHARS,
    REDACTED_PLACEHOLDER,
    redact_data,
    redact_text,
    redaction_values,
)

from .schedule import (  # noqa: F401
    DEFAULT_TIMEZONE,
    FIRE_KEY_LENGTH,
    INTERVAL_MAX_SECONDS,
    INTERVAL_MIN_SECONDS,
    SEARCH_HORIZON_DAYS,
    CronExpression,
    IntervalSchedule,
    ScheduleError,
    fire_key,
    next_occurrence,
    resolve_timezone,
)
