const LOCAL_SCHEMES = new Set(["about:", "blob:", "data:"]);
const READ_ONLY_METHODS = new Set(["GET", "HEAD", "OPTIONS"]);
const REDIRECT_STATUS_MIN = 300;
const REDIRECT_STATUS_MAX = 399;
const FORWARD_REQUEST_TIMEOUT_MS = 30_000;
const TRANSPORT_OWNED_REQUEST_HEADERS = new Set([
  "connection",
  "content-length",
  "host",
  "keep-alive",
  "proxy-authorization",
  "proxy-connection",
  "te",
  "trailer",
  "transfer-encoding",
  "upgrade",
]);

export const NO_REDIRECT_OR_RETRY = Object.freeze({ maxRedirects: 0, maxRetries: 0 });

/**
 * Build the options used by the isolated APIRequestContext forwarder.
 *
 * Chromium has already decided which end-to-end headers, notably Cookie and
 * Authorization, belong on this request. The Node transport must not consult
 * its own cookie jar when Chromium deliberately omitted Cookie, so an explicit
 * empty Cookie header is retained. Hop-by-hop headers, Host and Content-Length
 * are regenerated by the target transport from the exact URL/body bytes.
 */
export function buildBrowserForwardOptions(method, headers, postDataBuffer) {
  const forwardedHeaders = {};
  let browserCookie = "";
  const transportOwnedHeaders = new Set(TRANSPORT_OWNED_REQUEST_HEADERS);
  for (const [rawName, rawValue] of Object.entries(headers ?? {})) {
    if (rawName.toLowerCase() !== "connection") continue;
    for (const token of String(rawValue).split(",")) {
      const name = token.trim().toLowerCase();
      if (name) transportOwnedHeaders.add(name);
    }
  }
  for (const [rawName, rawValue] of Object.entries(headers ?? {})) {
    const name = rawName.toLowerCase();
    if (name === "cookie") {
      browserCookie = String(rawValue);
      continue;
    }
    if (transportOwnedHeaders.has(name)) continue;
    forwardedHeaders[name] = String(rawValue);
  }
  forwardedHeaders.cookie = browserCookie;

  const options = {
    ...NO_REDIRECT_OR_RETRY,
    failOnStatusCode: false,
    headers: forwardedHeaders,
    method: String(method),
    timeout: FORWARD_REQUEST_TIMEOUT_MS,
  };
  if (postDataBuffer !== null && postDataBuffer !== undefined) {
    options.data = postDataBuffer;
  }
  return options;
}

function asHttpOrigin(url) {
  if (url.protocol === "http:" || url.protocol === "https:") return url.origin;
  if (url.protocol !== "ws:" && url.protocol !== "wss:") return null;
  const counterpart = new URL(url.href);
  counterpart.protocol = url.protocol === "ws:" ? "http:" : "https:";
  return counterpart.origin;
}

/**
 * Classify every URL observed by the browser. WebSocket origins are compared
 * through their HTTP(S) counterpart, while a deliberately small set of local
 * browser schemes remains available. Any unknown scheme is a violation rather
 * than an implicit allow.
 */
export function evaluateBrowserTarget(rawUrl, allowedOrigins) {
  let url;
  try {
    url = new URL(rawUrl);
  } catch {
    return Object.freeze({ allowed: false, kind: "invalid", origin: null });
  }

  if (LOCAL_SCHEMES.has(url.protocol)) {
    return Object.freeze({ allowed: true, kind: "local", origin: null });
  }

  const origin = asHttpOrigin(url);
  if (origin === null) {
    return Object.freeze({ allowed: false, kind: "unexpected-scheme", origin: null });
  }
  const kind = url.protocol === "ws:" || url.protocol === "wss:" ? "websocket" : "http";
  return Object.freeze({ allowed: allowedOrigins.has(origin), kind, origin });
}

/** Return true only for the one credential-bearing mutation allowed by the journey. */
export function isExactLoginRequest(rawUrl, method, apiOrigin) {
  if (String(method).toUpperCase() !== "POST") return false;
  try {
    const url = new URL(rawUrl);
    return url.origin === apiOrigin
      && url.pathname === "/auth/login"
      && url.search === ""
      && url.hash === "";
  } catch {
    return false;
  }
}

export function isRedirectStatus(status) {
  return Number.isInteger(status) && status >= REDIRECT_STATUS_MIN && status <= REDIRECT_STATUS_MAX;
}

/**
 * The browser journey is read-only after authentication. Only the exact login
 * endpoint may use a mutating verb; every other POST/PUT/PATCH/DELETE request is
 * rejected even when its origin is otherwise trusted.
 */
export function isAllowedBrowserRequest(rawUrl, method, allowedOrigins, apiOrigin) {
  const target = evaluateBrowserTarget(rawUrl, allowedOrigins);
  if (!target.allowed) return false;

  const normalizedMethod = String(method).toUpperCase();
  if (READ_ONLY_METHODS.has(normalizedMethod)) return true;
  if (normalizedMethod !== "POST" || target.kind !== "http") return false;

  return isExactLoginRequest(rawUrl, normalizedMethod, apiOrigin);
}

/**
 * Stateful admission for the BrowserContext route. The first exact login POST
 * is admitted for a real, non-following fetch; all subsequent attempts fail
 * closed before reaching the network.
 */
export function createBrowserRequestGate(allowedOrigins, apiOrigin) {
  let loginAttempts = 0;
  return Object.freeze({
    authorize(rawUrl, method) {
      const exactLogin = isExactLoginRequest(rawUrl, method, apiOrigin);
      if (exactLogin) {
        loginAttempts += 1;
        const admittedByNetworkPolicy = isAllowedBrowserRequest(
          rawUrl,
          method,
          allowedOrigins,
          apiOrigin,
        );
        const allowed = admittedByNetworkPolicy && loginAttempts === 1;
        return Object.freeze({
          allowed,
          exactLogin: true,
          reason: !admittedByNetworkPolicy
            ? "network-policy"
            : (loginAttempts === 1 ? "login" : "duplicate-login"),
        });
      }
      const allowed = isAllowedBrowserRequest(rawUrl, method, allowedOrigins, apiOrigin);
      return Object.freeze({
        allowed,
        exactLogin: false,
        reason: allowed ? "read" : "network-policy",
      });
    },
    snapshot() {
      return Object.freeze({ loginAttempts });
    },
  });
}

function normalizedHeaderMap(headers) {
  const normalized = new Map();
  for (const [name, value] of Object.entries(headers ?? {})) {
    normalized.set(name.toLowerCase(), String(value).trim());
  }
  return normalized;
}

function headerTokens(value, { caseInsensitive = false } = {}) {
  const tokens = String(value ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
  return caseInsensitive ? tokens.map((item) => item.toLowerCase()) : tokens;
}

/**
 * Validate the real server response to the credentialed login preflight. This
 * is deliberately pure so the strict contract remains covered without a live
 * target in the default test suite.
 */
export function evaluateCredentialedLoginPreflight(status, headers, appOrigin) {
  if (!Number.isInteger(status) || status < 200 || status >= 300) {
    return Object.freeze({ allowed: false, reason: "status" });
  }
  const values = normalizedHeaderMap(headers);
  const responseVerdict = evaluateCredentialedCorsResponse(headers, appOrigin);
  if (!responseVerdict.allowed) return responseVerdict;
  if (!headerTokens(values.get("access-control-allow-methods")).includes("POST")) {
    return Object.freeze({ allowed: false, reason: "method" });
  }
  if (!headerTokens(
    values.get("access-control-allow-headers"),
    { caseInsensitive: true },
  ).includes("content-type")) {
    return Object.freeze({ allowed: false, reason: "header" });
  }
  return Object.freeze({ allowed: true, reason: "ok" });
}

/** Validate the CORS headers on the real credential-bearing POST response. */
export function evaluateCredentialedCorsResponse(headers, appOrigin) {
  const values = normalizedHeaderMap(headers);
  if (values.get("access-control-allow-origin") !== appOrigin) {
    return Object.freeze({ allowed: false, reason: "origin" });
  }
  if (values.get("access-control-allow-credentials") !== "true") {
    return Object.freeze({ allowed: false, reason: "credentials" });
  }
  return Object.freeze({ allowed: true, reason: "ok" });
}

/** A diagnostic label that deliberately drops credentials, query and fragment. */
export function safeBrowserTargetLabel(rawUrl, method = "CONNECT") {
  try {
    const url = new URL(rawUrl);
    if (!["http:", "https:", "ws:", "wss:"].includes(url.protocol)) {
      return `${method} ${url.protocol}<expurgé>`;
    }
    const authority = url.host ? `//${url.host}` : "";
    return `${method} ${url.protocol}${authority}${url.pathname}`;
  } catch {
    return `${method} URL invalide`;
  }
}
