// Catalogue UNIQUE des chaînes françaises des greffons acp-interface et acp-catalogue.
//
// Règles, vérifiées par tests/chaines.test.ts (arbre syntaxique TypeScript) et par le test
// navigateur (hermes/tests/e2e/test_interface_fr.py) :
// - tout texte visible et tout attribut lisible (title, aria-label, placeholder, alt, label) des
//   composants vient d'ici ; une valeur venue de l'API est rendue dans un élément data-acp-donnee ;
// - typographie française : espace insécable (U+00A0) avant « : ; ! ? » et à l'intérieur des
//   guillemets « » ; points de suspension en un seul caractère (…).
// Ce fichier ne contient que des chaînes (aucune fonction) : node --experimental-strip-types
// l'importe tel quel pour le test navigateur (outils/exporter-chaines.mjs).

export const T = {
  commun: {
    inconnu: "Inconnu",
    oui: "Oui",
    non: "Non",
    separateur: "·",
    chargement: "Chargement…",
    detailTechnique: "Détail technique",
    nonConfigure: "Non configuré",
  },
  marque: {
    sigle: "ACP",
    lienAccueil: "ACP, retour à l'accueil",
  },
  etats: {
    conforme: "Conforme",
    nonConforme: "Non conforme",
    inconnu: "Inconnu",
    nonConfigure: "Non configuré",
    horsLigne: "Hors ligne",
    connecte: "Connecté",
    active: "Active",
    activee: "Activée",
    desactivee: "Désactivée",
    absente: "Absente",
    candidate: "Candidate pour le poste, non planifiée",
    prevueP8: "Prévu au poste (P8)",
    horsV1: "Hors v1",
    ambigue: "Nom ambigu",
    livree: "Livrée",
    aJour: "À jour",
    deposee: "Déposée à ce démarrage",
    divergente: "Modifiée par le propriétaire",
    nonOrdinaire: "Fichier non ordinaire",
    presente: "Présente",
  },
  accueil: {
    titre: "Accueil",
    intro: "État de votre agent Hermes et de la plateforme ACP, relevé à l'ouverture de la page.",
    hermes: "Hermes",
    version: "Version en service",
    versionTestee: "Version testée par ACP",
    conformite: "Conformité",
    image: "Image de base",
    commit: "Commit déployé",
    garde: "Garde d'exécution",
    gardeEtat: "Processus du tableau de bord",
    gardeActive: "Active",
    gardeAbsente: "Absente",
    outilsAdmis: "Outils admis pour l'agent",
    persona: "Persona",
    personaEtat: "SOUL.md",
    catalogue: "Catalogue",
    skillsAcp: "Skills ACP actives",
    skillsAttendues: "attendues",
    context7: "context7",
    ouvrirCatalogue: "Ouvrir le catalogue",
    sessions: "Sessions récentes",
    aucuneSession: "Aucune session pour l'instant.",
    sansTitre: "Sans titre",
    messages: "messages",
    toutesSessions: "Toutes les sessions",
    poste: "Poste Windows",
    posteNote: "Le poste du propriétaire n'est pas encore branché : il le sera à l'étape P5.",
    raccourcis: "Raccourcis",
    discussion: "Discussion",
    lienSessions: "Sessions",
    kanban: "Kanban",
    lienCatalogue: "Catalogue",
    piedAcp: "ACP",
    piedPropulse: "propulsé par Hermes Agent",
    piedLicence: "(licence MIT)",
    metaIndisponible: "L'état de la plateforme est indisponible : la route /v1/meta du greffon acp-poste ne répond pas.",
  },
  catalogue: {
    titre: "Catalogue",
    intro: "Skills et serveurs MCP retenus par ACP, en lecture seule : rien ne s'installe depuis cette page.",
    filtres: "Filtres",
    profil: "Profil",
    source: "Source",
    cible: "Cible",
    tous: "Tous",
    toutes: "Toutes",
    profilBase: "Base",
    profilWeb: "Site web",
    profilRecherche: "Recherche",
    profilDonnees: "Données",
    cibleHermes: "Hermes (Railway)",
    ciblePoste: "Poste Windows",
    skills: "Skills",
    mcp: "Serveurs MCP",
    nom: "Nom",
    description: "Description",
    etat: "État",
    licence: "Licence",
    outils: "Outils exposés",
    aucuneEntree: "Aucune entrée pour ces filtres.",
    ecarts: "Écarts",
    aucunEcart: "Aucun écart relevé.",
    horsCatalogue: "Installées hors catalogue",
    collisions: "Collisions de noms",
    desactivationsNonAppliquees: "Désactivations non appliquées",
    indisponible: "Catalogue ACP indisponible : le greffon acp-poste ne sert pas la route /v1/catalogue.",
    alertes: "Alertes du catalogue",
    vuParHermes: "Vu par le tableau de bord de Hermes",
    vuParHermesNote: "Liste renvoyée par /api/skills, telle que le tableau de bord la calcule.",
    skillsInstallees: "Skills installées",
    skillsActivees: "Activées",
    skillsDesactivees: "Désactivées",
    listeSkills: "Liste des skills",
  },
  alertes: {
    titre: "Alertes ACP",
  },
  refus: {
    sdk: "Interface ACP désactivée : SDK du tableau de bord incompatible.",
    attendu: "Attendu :",
    trouve: "Trouvé :",
  },
  erreurs: {
    requete: "La requête a échoué.",
    code: "Code HTTP",
    reseau: "Le tableau de bord ne répond pas.",
    inattendue: "Erreur inattendue.",
  },
} as const;
