// Catalogue UNIQUE des chaînes françaises des greffons acp-interface, acp-catalogue et acp-projets.
//
// Règles, vérifiées par tests/chaines.test.ts (arbre syntaxique TypeScript) et par le test
// navigateur (hermes/tests/e2e/test_interface_fr.py) :
// - tout texte visible et tout attribut lisible (title, aria-label, placeholder, alt, label) des
//   composants vient d'ici ; une valeur venue de l'API est rendue dans un élément data-acp-donnee ;
// - typographie française : espace insécable (U+00A0) avant « : ; ! ? » et à l'intérieur des
//   guillemets « » ; points de suspension en un seul caractère (…).
// Ce fichier ne contient que des chaînes (aucune fonction) : node --experimental-strip-types
// l'importe tel quel pour le test navigateur (outils/exporter-chaines.mjs).

export const T = {
  commun: {
    inconnu: "Inconnu",
    oui: "Oui",
    non: "Non",
    separateur: "·",
    chargement: "Chargement…",
    detailTechnique: "Détail technique",
    nonConfigure: "Non configuré",
  },
  marque: {
    sigle: "ACP",
    lienAccueil: "ACP, retour à l'accueil",
  },
  etats: {
    conforme: "Conforme",
    nonConforme: "Non conforme",
    inconnu: "Inconnu",
    nonConfigure: "Non configuré",
    horsLigne: "Hors ligne",
    connecte: "Connecté",
    active: "Active",
    activee: "Activée",
    desactivee: "Désactivée",
    absente: "Absente",
    candidate: "Candidate pour le poste, non planifiée",
    prevueP8: "Prévu au poste (P8)",
    horsV1: "Hors v1",
    ambigue: "Nom ambigu",
    livree: "Livrée",
    aJour: "À jour",
    deposee: "Déposée à ce démarrage",
    divergente: "Modifiée par le propriétaire",
    nonOrdinaire: "Fichier non ordinaire",
    presente: "Présente",
  },
  accueil: {
    titre: "Accueil",
    intro: "État de votre agent Hermes et de la plateforme ACP, relevé à l'ouverture de la page.",
    hermes: "Hermes",
    version: "Version en service",
    versionTestee: "Version testée par ACP",
    conformite: "Conformité",
    image: "Image de base",
    commit: "Commit déployé",
    garde: "Garde d'exécution",
    gardeEtat: "Processus du tableau de bord",
    gardeActive: "Active",
    gardeAbsente: "Absente",
    outilsAdmis: "Outils admis pour l'agent",
    persona: "Persona",
    personaEtat: "SOUL.md",
    catalogue: "Catalogue",
    skillsAcp: "Skills ACP actives",
    skillsAttendues: "attendues",
    context7: "context7",
    ouvrirCatalogue: "Ouvrir le catalogue",
    sessions: "Sessions récentes",
    aucuneSession: "Aucune session pour l'instant.",
    sansTitre: "Sans titre",
    messages: "messages",
    toutesSessions: "Toutes les sessions",
    poste: "Poste Windows",
    posteNote: "Le poste du propriétaire n'est pas encore branché : il le sera à l'étape P5.",
    raccourcis: "Raccourcis",
    lienProjets: "Projets",
    discussion: "Discussion",
    lienSessions: "Sessions",
    kanban: "Kanban",
    lienCatalogue: "Catalogue",
    piedAcp: "ACP",
    piedPropulse: "propulsé par Hermes Agent",
    piedLicence: "(licence MIT)",
    metaIndisponible: "L'état de la plateforme est indisponible : la route /v1/meta du greffon acp-poste ne répond pas.",
  },
  catalogue: {
    titre: "Catalogue",
    intro: "Skills et serveurs MCP retenus par ACP, en lecture seule : rien ne s'installe depuis cette page.",
    filtres: "Filtres",
    profil: "Profil",
    source: "Source",
    cible: "Cible",
    tous: "Tous",
    toutes: "Toutes",
    profilBase: "Base",
    profilWeb: "Site web",
    profilRecherche: "Recherche",
    profilDonnees: "Données",
    cibleHermes: "Hermes (Railway)",
    ciblePoste: "Poste Windows",
    skills: "Skills",
    mcp: "Serveurs MCP",
    nom: "Nom",
    description: "Description",
    etat: "État",
    licence: "Licence",
    outils: "Outils exposés",
    aucuneEntree: "Aucune entrée pour ces filtres.",
    ecarts: "Écarts",
    aucunEcart: "Aucun écart relevé.",
    horsCatalogue: "Installées hors catalogue",
    collisions: "Collisions de noms",
    desactivationsNonAppliquees: "Désactivations non appliquées",
    indisponible: "Catalogue ACP indisponible : le greffon acp-poste ne sert pas la route /v1/catalogue.",
    alertes: "Alertes du catalogue",
    vuParHermes: "Vu par le tableau de bord de Hermes",
    vuParHermesNote: "Liste renvoyée par /api/skills, telle que le tableau de bord la calcule.",
    skillsInstallees: "Skills installées",
    skillsActivees: "Activées",
    skillsDesactivees: "Désactivées",
    listeSkills: "Liste des skills",
  },
  alertes: {
    titre: "Alertes ACP",
  },
  projets: {
    titre: "Projets",
    intro: "Les projets que vous confiez à Hermes : il les planifie, les fait avancer carte par carte et vous pose ici ses questions.",
    navigation: "Pages des projets",
    vueListe: "Projets",
    vueQuestions: "Questions",
    vueNouveau: "Nouveau projet",
    actualisation: "Page actualisée toutes les 15 secondes tant qu'elle est visible.",
    actualisationImpossible: "Dernière actualisation impossible : les données affichées sont celles de la lecture précédente.",
    indisponible: "Les projets sont indisponibles : le greffon acp-poste ne répond pas sur /v1/projets.",
    questionsIndisponibles: "Les questions sont indisponibles : le greffon acp-poste ne répond pas sur /v1/questions.",
    posteIndisponible: "L'inventaire du poste est indisponible : le greffon acp-poste ne répond pas sur /v1/poste.",
    envoi: "Envoi…",
    vosProjets: "Vos projets",
    nouveauProjet: "Nouveau projet",
    aucunProjet: "Aucun projet pour l'instant. Lancez-en un avec « Nouveau projet », ou demandez-le à Hermes dans la discussion.",
    cartesFaites: "Cartes faites",
    sur: "sur",
    enAttenteDuPoste: "Cartes en attente du poste",
    bloquees: "Cartes bloquées",
    enTriage: "Cartes en triage",
    questionsEnAttente: "Questions en attente",
    derniereNote: "Dernière note",
    aucuneNote: "Aucune carte finie pour l'instant.",
    poste: "Poste",
    depuis: "depuis",
    depuisLe: "Depuis",
    creeLe: "Créé",
    termineLe: "Terminé",
    etat: "État",
    posteTitre: "Poste Windows",
    machine: "Machine",
    derniereVue: "Vu pour la dernière fois",
    cartesEnAttente: "Cartes du poste en attente",
    notificationsTitre: "Notifications",
    canal: "Canal",
    canalAucun: "Aucun",
    canalTelegram: "Telegram",
    canalNtfy: "ntfy",
    etatNotifications: "État",
    notificationsActives: "Configurées",
    notificationsInactives: "Non configurées",
    notificationsNonConfigurees: "Notifications non configurées (variables ACP_NOTIFICATIONS… du service Hermes sur Railway).",
    envoyerTest: "Envoyer une notification de test",
    pauseTitre: "Pause générale",
    pauseExplication: "Arrête tout le travail de Hermes : aucune nouvelle carte ne part et les cartes en cours finissent. Aucune notification pendant la pause.",
    pauseGenerale: "Pause générale",
    pauseQuestion: "Mettre Hermes en pause générale ?",
    pauseConfirmer: "Confirmer la pause générale",
    annuler: "Annuler",
    pauseEnCours: "Hermes est en pause générale",
    pauseEffet: "Aucune nouvelle carte ne part tant que vous ne reprenez pas.",
    raison: "Raison",
    reprendreHermes: "Reprendre",
    nouveauTitre: "Nouveau projet",
    nouveauIntro: "Décrivez le résultat attendu : Hermes le découpe en étapes vérifiables et le fait avancer seul. Il ne pousse, ne fusionne et ne publie jamais sans votre accord.",
    champTitre: "Titre",
    champObjectif: "Objectif",
    aideObjectif: "Ce qui doit exister à la fin, les contraintes et ce qui compte pour vous.",
    champProfil: "Type de projet",
    champReponses: "Qui répond aux questions",
    reponsesHermes: "Hermes d'abord",
    reponsesHermesAide: "Hermes répond s'il le peut à partir de l'objectif et des décisions du projet ; sinon, il vous transmet la question.",
    reponsesProprietaire: "Moi",
    reponsesProprietaireAide: "Chaque question vous est transmise directement.",
    champDepot: "Dépôt",
    sansDepot: "Sans dépôt",
    aucunDepotConnu: "Aucun dépôt connu : le poste n'a encore publié aucun inventaire (étape P5).",
    releveFactice: "Relevé factice : ces modèles viennent d'un relevé de test, pas de votre poste.",
    exploration: "Exploration du dépôt",
    explorationAide: "Le poste lit le dépôt, sans rien y modifier, avant la planification.",
    champVoie: "Exécutant",
    champModele: "Modèle",
    modeleParDefaut: "Modèle par défaut du relevé",
    champEffort: "Effort",
    effortParDefaut: "Par défaut",
    releveDu: "Relevé du",
    relevePerime: "Relevé périmé : le poste doit publier un nouvel inventaire.",
    lancer: "Lancer le projet",
    retour: "Retour aux projets",
    objectif: "Objectif",
    tour: "Tour",
    cartesCreees: "Cartes créées",
    correctionsParEtape: "Corrections par étape au plus",
    profil: "Type de projet",
    depot: "Dépôt",
    reponses: "Qui répond",
    origine: "Lancé depuis",
    origineTableau: "la page Projets",
    origineDiscussion: "la discussion",
    mettreEnPause: "Mettre en pause",
    reprendre: "Reprendre",
    cartes: "Cartes",
    aucuneCarte: "Aucune carte pour l'instant.",
    statut: "Statut",
    voie: "Exécutant",
    modeleDemande: "Modèle demandé",
    effort: "Effort",
    palier: "Palier",
    modeleServi: "Modèle servi",
    mention: "Mention",
    carte: "Carte",
    resume: "Résumé",
    toursTitre: "Tours et décisions",
    decisions: "Décisions",
    voirQuestions: "Voir les questions",
    journal: "Journal",
    journalVide: "Journal vide.",
    journalOuvrir: "Entrées du journal",
    questionsTitre: "Questions ouvertes",
    aucuneQuestion: "Aucune question en attente.",
    projet: "Projet",
    motifEscalade: "Motif",
    poseeLe: "Posée",
    votreReponse: "Votre réponse",
    repondre: "Répondre",
    reponseEnvoyee: "Réponse envoyée : la carte reprend.",
    triageTitre: "Cartes en triage",
    aucunTriage: "Aucune carte en triage.",
    consigne: "Consigne (facultative)",
    reprendreCarte: "Reprendre",
    carteReprise: "Carte reprise : elle repart dans le graphe du projet.",
    bloqueesTitre: "Cartes bloquées ou abandonnées",
    bloqueesNote: "Lecture seule : relancer une carte depuis cette page arrivera à l'étape P7 ; en attendant, le kanban de Hermes le permet.",
    aucuneBloquee: "Aucune carte bloquée.",
    abandonnee: "Abandonnée après plusieurs échecs",
    assigne: "Assignée à",
    tableauxIllisibles: "Tableaux illisibles",
    etats: {
      creation: "Création en cours",
      actif: "Actif",
      enPause: "En pause",
      termine: "Terminé",
      abandonne: "Abandonné",
      exploration: "Exploration du dépôt",
      planification: "Planification",
      synthese: "Synthèse",
      enCours: "En cours",
      enAttenteDuPoste: "En attente du poste",
      plafondAtteint: "Plafond atteint : votre décision est attendue",
    },
    statuts: {
      triage: "En triage",
      todo: "En attente",
      scheduled: "Suspendue",
      ready: "Prête",
      running: "En cours",
      blocked: "Bloquée",
      review: "En relecture",
      done: "Faite",
      archived: "Archivée",
      aCreer: "À créer",
    },
    roles: {
      exploration: "Exploration du dépôt",
      planification: "Planification",
      implementation: "Implémentation",
      relecture: "Relecture croisée",
      correction: "Corrections",
      hermes: "Étapes de Hermes",
      synthese: "Synthèse",
      repondre: "Réponses aux questions",
      triage: "Triage",
    },
    voies: {
      hermes: "Hermes",
      posteCodex: "Poste (Codex)",
      posteClaude: "Poste (Claude)",
    },
    etatsPoste: {
      nonConfigure: "Non configuré",
      enLigne: "En ligne",
      horsLigne: "Hors ligne",
    },
    etatsQuestion: {
      ouverte: "Hermes cherche la réponse",
      escaladee: "Votre réponse est attendue",
    },
  },
  refus: {
    sdk: "Interface ACP désactivée : SDK du tableau de bord incompatible.",
    attendu: "Attendu :",
    trouve: "Trouvé :",
  },
  erreurs: {
    requete: "La requête a échoué.",
    code: "Code HTTP",
    reseau: "Le tableau de bord ne répond pas.",
    inattendue: "Erreur inattendue.",
  },
} as const;
